// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnmMdvfVkKKIoSwMcJhaiaXRCuAudPTro',
    appId: '1:67280778459:web:b5faef63115e084f7cc8fe',
    messagingSenderId: '67280778459',
    projectId: 'admotion-media-1',
    authDomain: 'admotion-media-1.firebaseapp.com',
    storageBucket: 'admotion-media-1.firebasestorage.app',
    measurementId: 'G-MTMKGLLP13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb2iIvZ1_HcG1plwuUYGG9wvr1ycEUACk',
    appId: '1:67280778459:android:477a2e5bf6c480db7cc8fe',
    messagingSenderId: '67280778459',
    projectId: 'admotion-media-1',
    storageBucket: 'admotion-media-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEC2aMC0NGkNrxK9SPJIeKGDCtKAWmcJw',
    appId: '1:67280778459:ios:96f42e0feb978a087cc8fe',
    messagingSenderId: '67280778459',
    projectId: 'admotion-media-1',
    storageBucket: 'admotion-media-1.firebasestorage.app',
    iosBundleId: 'com.admotion.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEC2aMC0NGkNrxK9SPJIeKGDCtKAWmcJw',
    appId: '1:67280778459:ios:96f42e0feb978a087cc8fe',
    messagingSenderId: '67280778459',
    projectId: 'admotion-media-1',
    storageBucket: 'admotion-media-1.firebasestorage.app',
    iosBundleId: 'com.admotion.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnmMdvfVkKKIoSwMcJhaiaXRCuAudPTro',
    appId: '1:67280778459:web:ab3788347c0206837cc8fe',
    messagingSenderId: '67280778459',
    projectId: 'admotion-media-1',
    authDomain: 'admotion-media-1.firebaseapp.com',
    storageBucket: 'admotion-media-1.firebasestorage.app',
    measurementId: 'G-S57ETD7H0W',
  );
}
